/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import com.virtualdogbert.HtmlEnforcer
import spock.lang.Specification

class HtmlEnforcerSpec extends Specification {
    def "validateHtml passing"() {
        setup:
            HtmlEnforcer htmlEnforcer = new HtmlEnforcer()

        when:
            boolean result = htmlEnforcer.validateHtml(html)

        then:
            result == testResult

        where:
            html                                                                                                         || testResult
            ''                                                                                                           || true
            '<a></a>'                                                                                                    || true
            """<p id=5 style="color:black">test</p> <script>alert('powed');</script>"""                                  || false
            "<a></a><p class='classy' style='color: blue;width:5%'>An <b>example</b> link.</p><img width=\"100\"></img>" || true
            "<p style='color: blue;width:5000em'></p>"                                                                   || true
            "<p style='width:5000em'></p>"                                                                               || true
            "<p style='background-attachment:fixed'></p>"                                                                || true
            "<p style='background-color:#FFFFFF'></p>"                                                                   || true
            """<p style='background-image:url("paper.gif")'></p>"""                                                      || true
            """<p style="background-image:url('paper.gif')"></p>"""                                                      || true
            """<p style="background-image:url('www.google.com/paper.gif')"></p>"""                                       || true
            "<p style='background-position:cenTer ToP'></p>"                                                             || true
            "<p style='background-position:50px 50px'></p>"                                                              || true
            "<p style='background-position:10% 10%'></p>"                                                                || true
            "<p style='background-repeat:repeat-x'></p>"                                                                 || true
            "<p style='border-bottom-color:red'></p>"                                                                    || true
            "<p style='border-bottom-width:medium'></p>"                                                                 || true
            "<p style='border-bottom-width:50px'></p>"                                                                   || true
            "<p style='border-color:#555'></p>"                                                                          || true
            "<p style='border-left-color:#213657'></p>"                                                                  || true
            "<p style='border-left-style:dotted'></p>"                                                                   || true
            "<p style='border-left-width:10px'></p>"                                                                     || true
            "<p style='border-right-color:GREEN'></p>"                                                                   || true
            "<p style='border-right-style:dashed'></p>"                                                                  || true
            "<p style='border-right-width:10px'></p>"                                                                    || true
            "<p style='border-style:inset'></p>"                                                                         || true
            "<p style='border-top-color:#123'></p>"                                                                      || true
            "<p style='border-top-style:groove'></p>"                                                                    || true
            "<p style='border-top-width:10px'></p>"                                                                      || true
            "<p style='border-bottom-style:dotted'></p>"                                                                 || true
            "<p style='border-width:10px'></p>"                                                                          || true
            "<p style='height:10px'></p>"                                                                                || true
            "<p style='outline-color:aqua'></p>"                                                                         || true
            "<p style='color:purple'></p>"                                                                               || true
    }

    def "validateHtml failing"() {
        setup:
            HtmlEnforcer htmlEnforcer = new HtmlEnforcer()

        when:
            boolean result = htmlEnforcer.validateHtml(html)

        then:
            result == testResult

        where:
            html                                       || testResult
            "<p style='background:10px'></p>"          || true
//            "<p style='border:10px'></p>"              || true
//            "<p style='border-bottom:10px'></p>"       || true
//            "<p style='border-left:10px'></p>"         || true
//            "<p style='border-right:10px'></p>"        || true
//            "<p style='border-top:10px'></p>"          || true
//            "<p style='clear:10px'></p>"               || true
//            "<p style='cursor:10px'></p>"              || true
//            "<p style='display:10px'></p>"             || true
//            "<p style='float:10px'></p>"               || true
//            "<p style='position:10px'></p>"            || true
//            "<p style='visibility:10px'></p>"          || true
//            "<p style='line-height:10px'></p>"         || true
//            "<p style='max-height:10px'></p>"          || true
//            "<p style='max-width:10px'></p>"           || true
//            "<p style='min-height:10px'></p>"          || true
//            "<p style='min-width:10px'></p>"           || true
//            "<p style='width:10px'></p>"               || true
//            "<p style='font:10px'></p>"                || true
//            "<p style='font-family:10px'></p>"         || true
//            "<p style='font-size:10px'></p>"           || true
//            "<p style='font-size-adjust:10px'></p>"    || true
//            "<p style='font-stretch:10px'></p>"        || true
//            "<p style='font-style:10px'></p>"          || true
//            "<p style='font-variant:10px'></p>"        || true
//            "<p style='font-weight:10px'></p>"         || true
//            "<p style='content:10px'></p>"             || true
//            "<p style='counter-increment:10px'></p>"   || true
//            "<p style='counter-reset:10px'></p>"       || true
//            "<p style='quotes:10px'></p>"              || true
//            "<p style='list-style:10px'></p>"          || true
//            "<p style='list-style-image:10px'></p>"    || true
//            "<p style='list-style-position:10px'></p>" || true
//            "<p style='list-style-type:10px'></p>"     || true
//            "<p style='marker-offset:10px'></p>"       || true
//            "<p style='margin:10px'></p>"              || true
//            "<p style='margin-bottom:10px'></p>"       || true
//            "<p style='margin-left:10px'></p>"         || true
//            "<p style='margin-right:10px'></p>"        || true
//            "<p style='margin-top:10px'></p>"          || true
//            "<p style='outline:10px'></p>"             || true
//            "<p style='outline-style:10px'></p>"       || true
//            "<p style='outline-width:10px'></p>"       || true
//            "<p style='padding:10px'></p>"             || true
//            "<p style='padding-bottom:10px'></p>"      || true
//            "<p style='padding-left:10px'></p>"        || true
//            "<p style='padding-right:10px'></p>"       || true
//            "<p style='padding-top:10px'></p>"         || true
//            "<p style='bottom:10px'></p>"              || true
//            "<p style='clip:10px'></p>"                || true
//            "<p style='left:10px'></p>"                || true
//            "<p style='overflow:10px'></p>"            || true
//            "<p style='position:10px'></p>"            || true
//            "<p style='right:10px'></p>"               || true
//            "<p style='top:10px'></p>"                 || true
//            "<p style='vertical-align:10px'></p>"      || true
//            "<p style='z-index:10px'></p>"             || true
//            "<p style='border-collapse:10px'></p>"     || true
//            "<p style='border-spacing:10px'></p>"      || true
//            "<p style='caption-side:10px'></p>"        || true
//            "<p style='empty-cells:10px'></p>"         || true
//            "<p style='table-layout:10px'></p>"        || true
//            "<p style='direction:10px'></p>"           || true
//            "<p style='line-height:10px'></p>"         || true
//            "<p style='letter-spacing:10px'></p>"      || true
//            "<p style='text-align:10px'></p>"          || true
//            "<p style='text-decoration:10px'></p>"     || true
//            "<p style='text-indent:10px'></p>"         || true
//            "<p style='text-shadow:10px'></p>"         || true
//            "<p style='text-transform:10px'></p>"      || true
//            "<p style='unicode-bidi:10px'></p>"        || true
//            "<p style='white-space:10px'></p>"         || true
//            "<p style='word-spacing:10px'></p>"        || true
//            "<p style='all:10px'></p>"                 || true
//            "<p style='aural:10px'></p>"               || true
//            "<p style='braille:10px'></p>"             || true
//            "<p style='embossed:10px'></p>"            || true
//            "<p style='handheld:10px'></p>"            || true
//            "<p style='print:10px'></p>"               || true
//            "<p style='projection:10px'></p>"          || true
//            "<p style='screen:10px'></p>"              || true
//            "<p style='tty:10px'></p>"                 || true
//            "<p style='tv:10px'></p>"                  || true
    }
}
