/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import com.virtualdogbert.HtmlEnforcer
import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new HtmlEnforcer()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
